- README.md
Added info to readme that sources depend on submodules.
> added info that solution contains submodules to readme

- README.md
- binder/Binder.cs
- binder/Compilation.cs
- binder/Options.cs
Defaults to latest, it lets you specify guys from VisualStudioVersion enum (minus VS prefix), so: 2012, 2013, 2015 and Latest.
#11
> added argument for Visual Studio version specification

- docs/error.md
- objcgen/ErrorHelper.cs
- objcgen/driver.cs
- objcgen/generator.cs
- objcgen/objcgenerator.cs
- tests/objcgentest/DriverTest.cs
- tests/objcgentest/ObjCGeneratorTest.cs
- tests/objcgentest/objcgentest.csproj
* EM0000 is now shown for unhandled exceptions - asking for a bug report
to be submitted;
* EM0001 is reported when the output directory cannot be found;
* EM1000 is reported when the generator throws a NotImplementedException,
no bug report is required, but contributions are welcome :)
> [objc] Add support for -o (output directory) and -v (verbosity) and add some error codes

- objcgen/objcgenerator.cs
so we don't have to to it twice - as filtering will only become more
complex over time.
Also sort the types so it's easier to find them (e.g. when listed in the
class forwarders) and adjust some WriteLine so make generated code easier
to read.
> [objc][generator] Use the already filtered `types` at generation time

- tests/managed/exceptions.cs
- tests/managed/managed.csproj
- tests/objc-cli/libmanaged/Tests/Tests.m
For
* instance properties (uncomment them);
* namespaces;
* exceptions inside `init`;
> [objc][tests] Add more unit tests for existing features

- docs/error.md
- objcgen/driver.cs
- tests/objcgentest/DriverTest.cs
This will help scripts to switch between implementations.
> [objc][driver] Command-line options parity with master

- objcgen/objcgenerator.cs
- tests/managed/namespaces.cs
- tests/objc-cli/libmanaged/Tests/Tests.m
- tests/objcgentest/ObjCGeneratorTest.cs
Not common, but has to work. Unit test added.
> [objc] The same type name can exists in several namespaces

- objcgen/driver.cs
- objcgen/objcgenerator.cs
- tests/objc-cli/.gitignore
- tests/objc-cli/Makefile
where release is non-debug.
https://github.com/mono/Embeddinator-4000/issues/82
> [objc][generator] Use metadata token lookup when building release

- docs/error.md
- objcgen/driver.cs
- objcgen/objcgen.csproj
- objcgen/objcgenerator-processor.cs
- objcgen/objcgenerator.cs
This allow the tool to produce something on existing binaries, which
will make testing easier as we go forward.
> [objc][processor] Filter and warn about unsupported C# features/types

- docs/error.md
that I forgot when adding the warning in a previous commit
> [objc][docs] Add missing documentation for EM1050

- .gitignore
- samples/Makefile
- samples/mac/weather/Makefile
- samples/mac/weather/MyManagedStuff/MyManagedStuff.sln
- samples/mac/weather/MyManagedStuff/MyManagedStuff/MyManagedStuff.csproj
- samples/mac/weather/MyManagedStuff/MyManagedStuff/Properties/AssemblyInfo.cs
- samples/mac/weather/MyManagedStuff/MyManagedStuff/WeatherFetcher.cs
- samples/mac/weather/README.md
- samples/mac/weather/theweather/theweather.xcodeproj/project.pbxproj
- samples/mac/weather/theweather/theweather.xcodeproj/project.xcworkspace/contents.xcworkspacedata
- samples/mac/weather/theweather/theweather/AppDelegate.h
- samples/mac/weather/theweather/theweather/AppDelegate.m
- samples/mac/weather/theweather/theweather/Assets.xcassets/AppIcon.appiconset/Contents.json
- samples/mac/weather/theweather/theweather/Base.lproj/Main.storyboard
- samples/mac/weather/theweather/theweather/Info.plist
- samples/mac/weather/theweather/theweather/ViewController.h
- samples/mac/weather/theweather/theweather/ViewController.m
- samples/mac/weather/theweather/theweather/main.m
This sample shows an Objective-C Mac app consuming a managed .NET assembly.
You'll find two solutions
* **MyManagedStuff**: Managed C# library.
* **theweather** : An Objective-C Xcode project for a Mac App.
In order to run this sample, you need to run `make` from the CLI, this will build the managed .NET library and use **Embeddinator-4000** on it to place the needed support files under `theweather/MyManagedStuff`. Once you have this files you can open `theweather` Xcode project and run it.
> [objc][samples] Add weather sample

- objcgen/objcgenerator.cs
This turns, mostly existing, comments into appedoc [1] compatible ones.
That makes our public contract easier to read and, optionally, able to
generate documentation inside Xcode using [2]
It also fix a _few_ nullability warnings from clang, since adding a
single `nullable` or `nonnull` makes clang complain about all potential
cases - even the ones marked with `NS_UNAVAILABLE`
references:
[1] http://nshipster.com/documentation/
[2] https://github.com/tomaz/appledoc
[3] https://github.com/mono/Embeddinator-4000/issues/112
> [objc] Use appledoc-style comments in the header files

- objcgen/extensions.cs
- objcgen/methodhelper.cs
- objcgen/objcgenerator-helpers.cs
- objcgen/objcgenerator-processor.cs
- objcgen/objcgenerator.cs
- tests/managed/methods.cs
- tests/objc-cli/libmanaged/Tests/Tests.m
Fix https://github.com/mono/Embeddinator-4000/issues/152
> [objc] Add support for extension methods using categories

- docs/error.md
- objcgen/Make.config
- objcgen/Makefile
- objcgen/driver.cs
- objcgen/objcgen.csproj
- objcgen/objcgenerator.cs
- objcgen/thin-framework.sh
- support/embeddinator.h
- support/mono-support.h
- support/mono_embeddinator.c
- support/mono_embeddinator.h
- tests/RunTestsuite.sh
- tests/objc-cli/Makefile
- tests/objc-cli/libmanaged-ios/libmanaged-ios.xcodeproj/project.pbxproj
- tests/objc-cli/libmanaged-ios/libmanaged-ios.xcodeproj/xcshareddata/xcschemes/libmanaged-ios.xcscheme
- tests/objc-cli/libmanaged-ios/libmanaged-ios/AppDelegate.h
- tests/objc-cli/libmanaged-ios/libmanaged-ios/AppDelegate.m
- tests/objc-cli/libmanaged-ios/libmanaged-ios/Assets.xcassets/AppIcon.appiconset/Contents.json
- tests/objc-cli/libmanaged-ios/libmanaged-ios/Base.lproj/LaunchScreen.storyboard
- tests/objc-cli/libmanaged-ios/libmanaged-ios/Base.lproj/Main.storyboard
- tests/objc-cli/libmanaged-ios/libmanaged-ios/Info.plist
- tests/objc-cli/libmanaged-ios/libmanaged-ios/ViewController.h
- tests/objc-cli/libmanaged-ios/libmanaged-ios/ViewController.m
- tests/objc-cli/libmanaged-ios/libmanaged-ios/main.m
- tests/objc-cli/libmanaged-ios/libmanaged-iosTests/Info.plist
- tests/objc-cli/libmanaged-ios/libmanaged-iosTests/libmanaged_iosTests.m
- tests/objc-cli/libmanaged/Tests/Tests.m
- tests/objc-cli/perf-test.m
- tests/objc-cli/test-managed.m
Add support for compiling to frameworks.
I've only tested iOS frameworks, tvOS and watchOS may or may not work.
macOS is not supported (and will show errors).
> [objc] Add support for compiling to frameworks.

- support/mono_embeddinator.c
> [C] Fixing bugs for windows compatibility

- objcgen/objcgen.csproj
- objcgen/objcgenerator.cs
- objcgen/sourcewriter.cs
* Allow enabling/disabling the writer (needed for other features like
protocols);
* Deal with tabs in a single place - so output looks better;
> [objc] Add a new SourceWriter to replace the TextWriter

- objcgen/objcgenerator-processor.cs
- objcgen/objcgenerator.cs
- tests/managed/constructors.cs
- tests/managed/methods.cs
- tests/objc-cli/libmanaged/Tests/Tests.m
- tests/objcgentest/ObjCGeneratorTest.cs
note: incomplete, non-integral types needs more love
> [objc] Add support for default values on .ctor/method parameters

- objcgen/generator.cs
- objcgen/objcgen.csproj
- objcgen/objcgenerator-helpers.cs
- objcgen/objcgenerator-postprocessor.cs
- objcgen/objcgenerator-processor.cs
- objcgen/objcgenerator-subscripts.cs
- objcgen/objcgenerator.cs
- objcgen/processedtypes.cs
- tests/managed/constructors.cs
- tests/managed/methods.cs
- tests/managed/properties.cs
- tests/objc-cli/libmanaged/Tests/Tests.m
Not ready to merge due to https://github.com/chamons/Embeddinator-4000/commit/6e4fb6403fe30833120f6edfcc65cc133f7bfc6e but I wanted to get something out there.
> Framework to handle duplicate identifiers via postprocessing

- binder/Compilation.cs
Should fix #165 
Signed-off-by: realvictorprm <mueller.vpr@gmail.com>
> [C / C++] Fixing windows compilation issues.

- objcgen/extensions.cs
- tests/objcgentest/ExtensionsTest.cs
and not just types. Add unit tests.
> [objc] Fix Implements extension method to work on interfaces

- objcgen/EqualsHelper.cs
- objcgen/HashHelper.cs
- objcgen/comparablehelper.cs
- objcgen/methodhelper.cs
- objcgen/sourcewriter.cs
Mostly remove tabulations from Write[Line] calls.
> [objc] Use SourceWriter from *Helper classes

- objcgen/classhelper.cs
- objcgen/objcgen.csproj
- objcgen/objcgenerator-subscripts.cs
- objcgen/objcgenerator.cs
ClassHelper will the addition of @protocol without duplicating too
much code.
Along with the move the remaining tabulation code to use Intent.
This makes the generated code (ainly the implementation) looks a lot
better.
> [objc] Add ClassHelper and use Indent for remaining tab support

- objcgen/EqualsHelper.cs
This will pick up the virtual call fix once PR #191 lands.
> [objc] Simplify EqualsHelper by calling WriteInvoke

- objcgen/NameGenerator.cs
- objcgen/objcgen.csproj
- objcgen/objcgenerator-helpers.cs
- objcgen/objcgenerator-subscripts.cs
- objcgen/objcgenerator.cs
- tests/objcgentest/ObjCGeneratorTest.cs
- Both to get more code out of objcgenerator*.cs and pave the way to possible future caching
> Centralize name generation in one place

- objcgen/extensions.cs
- objcgen/generator.cs
- objcgen/objcgenerator-helpers.cs
- objcgen/objcgenerator-processor.cs
- objcgen/objcgenerator.cs
- objcgen/processedtypes.cs
- Have ProcessedType join it's cousins. No post processing yet, but it allows caching of names.
- https://github.com/mono/Embeddinator-4000/issues/155
> ProcessedType and Name Caching

- objcgen/objcgenerator-subscripts.cs
- tests/managed/subscripts.tt
- https://github.com/mono/Embeddinator-4000/issues/239
> Fix silly subsript restriction on read/write only properties

- objcgen/NameGenerator.cs
- objcgen/extensions.cs
- objcgen/objcgenerator-helpers.cs
- tests/managed/overloads.cs
- tests/objc-cli/libmanaged/Tests/Tests.m
- https://github.com/mono/Embeddinator-4000/issues/207
- Also refactor GetSignatures a bit
> Mutate operator methods that are in duplicate

- objcgen/EqualsHelper.cs
- objcgen/objcgenerator-postprocessor.cs
- objcgen/objcgenerator-processor.cs
- objcgen/operatoroverloads.cs
- objcgen/processedtypes.cs
- tests/managed/overloads.cs
- tests/objc-cli/libmanaged/Tests/Tests.m
https://github.com/mono/Embeddinator-4000/issues/221
> Handle Equality Operators Better

- docs/getting-started-objective-c.md
> [objc][docs] Fix relative links in getting-started-objective-c

- objcgen/.gitignore
- objcgen/Makefile
- objcgen/driver.cs
- objcgen/generate-version.sh
- objcgen/script/objcgen
- This will likely become more complicated in the future, but is good enough to start out with.
- https://github.com/mono/Embeddinator-4000/issues/222
> Simple Packaging and Installer Scripts

- docs/getting-started-objc-ios.md
- docs/getting-started-objc-macos.md
- docs/getting-started-objective-c.md
- objcgen/Makefile
- https://github.com/mono/Embeddinator-4000/issues/268
> Fix installer location

- objcgen/processor.cs
- Process the type queue while processing the assembly one (not after);
- Add `AddExtraType` so it's possible to add external/additional code to
be included (e.g. issues #175 and #176);
- Make sure it's safe to call `GetProcessedType` (or throw)
references:
* https://github.com/mono/Embeddinator-4000/issues/175
* https://github.com/mono/Embeddinator-4000/issues/176
> [objc] Give the processor the ability to add external/additional code

- objcgen/NameGenerator.cs
- objcgen/extensions.cs
- objcgen/objcgenerator-helpers.cs
- objcgen/objcgenerator.cs
- objcgen/objcprocessor.cs
- support/mono-support.h
- tests/managed/arrays.cs
- tests/managed/managed-shared.projitems
- tests/objc-cli/libmanaged/Tests/Tests.m
> [objc] Add Array support

- docs/errors.md
- objcgen/driver.cs
- objcgen/objcgen.csproj
- objcgen/system-check.cs
> [objc] Add system checks with hopefully helpful error messages. Fixes issue #286.

- docs/getting-started-objc-ios.md
- docs/getting-started-objective-c.md
- docs/releases/Embeddinator-4000_0.1.md
Also
- remove some duplication from getting-started-objc-ios.md
- pick up some changes from PR #272 [1]
- typos
[1] https://github.com/mono/Embeddinator-4000/pull/272
> [objc][docs] Add initial release notes and a few other doc updates

- objcgen/objcgenerator-helpers.cs
- objcgen/objcgenerator-postprocessor.cs
- objcgen/objcgenerator.cs
- objcgen/operatoroverloads.cs
- tests/objc-cli/libmanaged/Tests/Tests.m
A fixed up https://github.com/mono/Embeddinator-4000/pull/289
> Handle operators (friendly and normal) name generation the same

- objcgen/objcgenerator.cs
* reduced if nesting for mono_array_set in NSNumbers
* Fixed indentation issue in generated code
> [objc] Fix indentation of generated code and reduce nesting

- tests/objc-cli/libmanaged/Tests/Tests.m
This was suggested here https://github.com/mono/Embeddinator-4000/pull/292#discussion_r115512852 by @spouliot
> [objc] Turn indetation spaces into tabs in libmanaged/Tests.m

- objcgen/NameGenerator.cs
- objcgen/driver.cs
- objcgen/objcgen.csproj
- objcgen/objcgenerator-helpers.cs
- objcgen/objcgenerator.cs
- objcgen/objcprocessor.cs
- support/linker.xml
- support/mono-support.h
- support/mono_embeddinator.c
- support/mono_embeddinator.h
- support/objc-support.h
- support/objc-support.m
- tests/managed/types.cs
- tests/objc-cli/libmanaged/Tests/Tests.m
> [objc] Add NSDecimalNumber <-> decimal support

- objcgen/processor.cs
> AddExtraType was trying to queue types to typesQueue before it was initialized

- docs/ObjC.md
- Behavior change here - https://github.com/mono/Embeddinator-4000/pull/290
- Originally noted here - https://github.com/mono/Embeddinator-4000/issues/204
> Update docs for friendly operator behavior change

- objcgen/generator.cs
- objcgen/objcgenerator-helpers.cs
- objcgen/objcgenerator-postprocessor.cs
- objcgen/objcgenerator.cs
- objcgen/objcprocessor.cs
- objcgen/processedtypes.cs
- https://github.com/mono/Embeddinator-4000/issues/276
> Move GetSignatures into ProcessedType hierarchy

- objcgen/methodhelper.cs
- support/mono-support.h
- tests/leaktest/Program.cs
- tests/objc-cli/libmanaged/Tests/Tests.m
> [objc] Make sure to attach/detach from threads. Fixes issue #357.

- support/mono-support.c
- support/mono-support.h
- support/mono_embeddinator.c
- support/mono_embeddinator.h
> Mono runtime symbols dynamic loading [part 1]

- objcgen/TypeMapper.cs
- objcgen/embedder.cs
- objcgen/extensions.cs
- objcgen/objcgen.csproj
- objcgen/objcgenerator-postprocessor.cs
- objcgen/objcprocessor.cs
- objcgen/processedtypes.cs
- objcgen/processor.cs
- tests/managed/interfaces.cs
- tests/managed/methods.cs
- https://github.com/mono/Embeddinator-4000/issues/369
> Implement TypeMapper to improve duplication code

- binder/Generators/AstGenerator.cs
- binder/Generators/C/CMarshal.cs
- binder/Generators/C/CTypes.cs
- binder/Generators/Java/JavaMarshal.cs
- binder/Generators/Java/JavaTypePrinter.cs
- support/c-support.c
- support/c-support.h
- support/java/Decimal.java
- support/java/Runtime.java
- tests/common/Tests.C.cpp
Partial fix for https://github.com/mono/Embeddinator-4000/issues/406
> [c][java] Implement Decimal types support

- support/java/android/AndroidRuntimeProvider.java
I have a branch where I am working on extending our tests, I can
hopefully add a test case for this there.
For now this fixes it, but we don’t have a proper test case yet.
Fixes #418
> [android] fix for casing on Java package name

- docs/android-callbacks.md
- docs/getting-started-java-android.md
- docs/getting-started-java.md
- Minor correction to callbacks documentation
- Added specific instructions for using Java 1.8
Applies to #448
> [docs] clarifications on Java 1.8 / Android Studio 3.0

- binder/Generators/AstGenerator.cs
- binder/Generators/C/CMarshal.cs
- binder/Generators/C/CSources.cs
- tests/common/Tests.C.cpp
- tests/managed/arrays.cs
These fixes get Mono.Game to generate and compile (https://github.com/mono/Embeddinator-4000/issues/438)
> [c] Fixed generation and marshaling for enum arrays

- binder/Generators/C/CMarshal.cs
- binder/Generators/C/CSources.cs
- binder/Generators/C/CTypes.cs
- binder/Generators/Java/JavaMarshal.cs
- binder/Generators/Java/JavaTypePrinter.cs
- support/mono_embeddinator.c
- tests/common/Tests.C.cpp
- tests/common/java/mono/embeddinator/Tests.java
- tests/managed/methods.cs
This PR intends to add support for ref/out class reference types in C and Java.
> [java][c] Implement support for ref/out reference types / classes.

- Embeddinator-4000.nuspec
- build.cake
Adds two new Cake tasks for creating and publishing a Nuget package of Embeddinator.
> [nuget] Nuget package creation & publishing

- docs/getting-started-java-android.md
- docs/getting-started-java.md
- tests/android/.idea/misc.xml
- tests/android/app/build.gradle
- tests/android/build.gradle
- tests/android/gradle/wrapper/gradle-wrapper.properties
Updated docs and test project for Android Studio 3.0 beta.
Overall the experience is a lot better:
- faster build times
- deprecated `jackOptions` is removed
- multidex can be turned off in our test project
> [android] Android Studio 3.0

- binder/Generators/AstGenerator.cs
- binder/Generators/Java/JavaMarshal.cs
- binder/Generators/Java/JavaSources.cs
- binder/Passes/InterfacesPass.cs
- tests/common/java/mono/embeddinator/Tests.java
- tests/managed/abstracts.cs
- tests/managed/managed-shared.projitems
Adds support for abstract class proxies like we do for interfaces.
Fixes generation for `MonoGame.Framework.dll`.
https://github.com/mono/Embeddinator-4000/issues/438
(wip, still missing some tests)
> [java] Abstract class proxies

- Embeddinator-4000.sln
- binder/Generators/AstGenerator.cs
- build/Tests.cake
- tests/common/Tests.C.cpp
- tests/managed/fsharp-generic/fsharp-generic.fsproj
- tests/managed/fsharp-generic/packages.config
- tests/managed/fsharp-shared/Hello.fs
Adding F# record generation test.
Adding F# nested module generation with test.
working on unicode support...
> Adding generic F# test suit.

- support/java/DesktopImpl.java
- support/java/Runtime.java
- support/mono_embeddinator.c
- support/mono_embeddinator.h
> Introduce an API for setting runtime assembly paths

- binder/CLI.cs
- binder/Compilation.cs
- binder/Driver.cs
- binder/Generators/Swift/SwiftGenerator.cs
- binder/Generators/Swift/SwiftMarshal.cs
- binder/Generators/Swift/SwiftSources.cs
- binder/Generators/Swift/SwiftTypePrinter.cs
- build/Tests.cake
- build/Utils.cake
- build/projects/Embeddinator-4000.csproj
- tests/common/swift/Tests.swift
As the title says, this is the initial bootstrapping code for a Swift backend.
This PR only contains code to for generation of the stubs for Swift classes, methods and enums.
And the basic infrastructure for compilation of generated Swift code as well as code for dealing and running the test suite for Swift code.
Marshalling work for each managed type will come in separate PRs.
> [swift] Bootstrap the Swift generator backend

- objcgen/driver.cs
Not sure why it was missed out for iOS compared to other platforms, but have now added appropriate parameters so that it is.
> Added: bitcode enabled for iOS

- binder/Generators/C/CMarshal.cs
- binder/Generators/C/CSources.cs
- binder/Generators/Java/JavaMarshal.cs
- binder/Generators/Java/JavaSources.cs
- binder/Generators/Marshal.cs
- binder/Generators/Swift/SwiftMarshal.cs
- binder/Generators/Swift/SwiftSources.cs
Just some refactoring and renaming, nothing to see here...
> [binder] Refactor marshaling classes

- objcgen/Makefile
I ran into this problem while experimenting with the Mac sample.
> Fix objcgen Makefile

- binder/Generators/Java/JavaMarshal.cs
- binder/Generators/Java/JavaTypePrinter.cs
- binder/Passes/FixMethodParametersPass.cs
- tests/managed/android/managed-android.csproj
- tests/managed/fsharp-android/fsharp-android.fsproj
- tests/managed/fsharp-generic/fsharp-generic.fsproj
- tests/managed/generic/managed-generic.csproj
- tests/managed/ios/managed-ios.csproj
- tests/managed/macos-full/managed-macos-full.csproj
- tests/managed/macos-modern/managed-macos-modern.csproj
- tests/managed/macos-system/managed-macos-system.csproj
- tests/managed/netstandard/managed-netstandard.csproj
- tests/managed/pcl/managed-pcl.csproj
- tests/managed/tvos/managed-tvos.csproj
- tests/managed/types.cs
Fixes https://github.com/mono/Embeddinator-4000/issues/571.
> [Java] Fixed generation for unsafe primitive pointer types

- objcgen/embedder.cs
- Fixes a pair of system test failures.
> Resolve XM System correctly by adding both mono _and_ XM directories.

- objcgen/Makefile
- https://github.com/mono/Embeddinator-4000/issues/622
> Fix Xamarin.Embeddinator-4000 installer

- docs/errors.md
- objcgen/driver.cs
- objcgen/embedder.cs
- https://github.com/mono/Embeddinator-4000/issues/197
> [objc] Only consider framework use cases supported

- objcgen/driver.cs
- objcgen/embedder.cs
- support/mono_embeddinator.c
As per...
https://github.com/mono/Embeddinator-4000/issues/484
I have implemented Rolph's feedback for Native exception handling for apple devices and seems to work great.
I have added a command line param ne/nativeexception which will make objcgen use the technique he mentioned
> Native exception handling

- docs/ObjC.md
- tests/managed/exceptions.cs
- tests/objc-cli/libmanaged/Tests/Tests.m
- tests/objcgentest/ManagedTest.cs
- https://github.com/mono/Embeddinator-4000/issues/633
- Patch up PR for https://github.com/mono/Embeddinator-4000/pull/629
> Add tests and documentation for ObjC exception PR

- build/Packaging.cake
- objcgen/Makefile
- objcgen/script/objcgen
- Fix existing cake script to Download-Xamarin-Android to generate external/Xamarin.Android folder
> [ObjC] Initial nuget support
