build/projects/Xamarin.Android.Tools.csproj

Xamarin.Android.Tools was contained files from obj directory. That prevented compilation thus I removed them. They were there by mistake anyway, I assume.

removed Xamarin.Android.Tools references to files in obj directory

---

binder/Compilation.cs

Currently the oldest VS version is used for compilation instead of newest (latest).

taking latest visual studio version, not oldest

---

support/mono_embeddinator.c

Current code crash like this:
2017-03-24 15:52:02.732 a.out[92593:125062863] -[NSAutoreleasePool new]: unrecognized selector sent to instance 0x7fa2d6512c50
2017-03-24 15:52:02.733 a.out[92593:125062863] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSAutoreleasePool new]: unrecognized selector sent to instance 0x7fa2d6512c50'
*** First throw call stack:
(
0   CoreFoundation                      0x00007fffd1e10e7b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fffe6a0bcad objc_exception_throw + 48
2   CoreFoundation                      0x00007fffd1e92cb4 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
3   CoreFoundation                      0x00007fffd1d82fb5 ___forwarding___ + 1061
4   CoreFoundation …

[support] Fix creation of the NSAutoreleasePool

---

support/mono_embeddinator.c
support/mono_embeddinator.h
tests/objc-cli/.gitignore
tests/objc-cli/libmanaged/Tests/Info.plist
tests/objc-cli/libmanaged/Tests/Tests.m
tests/objc-cli/libmanaged/libmanaged.xcodeproj/project.pbxproj

This allows debugging the generated code with Xcode as well as
running the native unit tests with XCTest (which might not be the
best tool but it's good to support).
This commit requires a addition to mono_embeddinator so we can
override where the assemblies are loaded from - we cannot assume
they will be with the executable (e.g. plugin) and we hit this
case with Xcode unit tests.

[objc] Add xcode support for objc-cli to build the libmanaged.dylib and it's unit tests

---

objcgen/driver.cs
tests/managed/Makefile
tests/objc-cli/Makefile
tests/objc-cli/libmanaged/libmanaged.xcodeproj/project.pbxproj
tests/objc-cli/libmanaged/libmanaged.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme

Remove the 'libmanaged' target from the Xcode test project, and instead link
with the libmanaged.dylib that the embeddinator compiles. This ensures we're
not compiling with different compiler flags in the Xcode project.
This also requires adding an rpath to the built library so that the test
executable can find it.
Also add makefile target to run the Xcode test project from the command line.

[objc][tests] Remove the 'libmanaged' target from the Xcode cli test project.

---

objcgen/driver.cs
objcgen/objcgenerator.cs
support/mono_embeddinator.c
tests/objc-cli/Makefile

Also remove the NSAutoreleasePool code, the current code doesn't build with ARC,
and in any case it's the consumer's responsibility to ensure there's an
NSAutoreleasePool on the stack.

[objc] Enforce ARC.

---

objcgen/objcgenerator.cs
tests/managed/constructors.cs
tests/objc-cli/libmanaged/Tests/Tests.m

E.g. `public class SuperUnique : Unique {}`
This raise an interesting issue (to be solved later) since ObjC and .NET
semantics differs for init*/.ctor. A test case (with a FIXME) is added.
and I now recall why headers were a bad idea:
./bindings.h:75:39: error: attempting to use the forward class 'Constructors_Unique' as superclass of 'Constructors_SuperUnique'
so the ordering of forwarders had to be altered a bit.

[objc][generator] Fix subclassing when both types are bound

---

objcgen/generator.cs
objcgen/objcgenerator.cs
tests/managed/properties.cs
tests/objc-cli/libmanaged/Tests/Tests.m
tests/objcgentest/ObjCGeneratorTest.cs

This also handle the case of setter-only properties (generated as a
set* method).
Unit tests added for existing methods (previously not generated)
Replace PR https://github.com/mono/Embeddinator-4000/pull/63

[objc] Initial support for methods

---

tests/leaktest/Program.cs

Use pid-specific control files so multiple leak tests can run in parallel.

[tests][leaktest] Use pid-specific control files.

---

tests/objc-cli/Makefile

That one is not a generated file

[test][objc] Fix Makefile not to delete leak-at-exit.c

---

objcgen/objcgenerator.cs

Sadly we can't easily test the presence (or absence) of `dealloc` as this
gets us an error:
> ARC forbids use of 'dealloc' in a @selector

[objc][generator] Do not generate a `dealloc` or the `_object` field for static types

---

objcgen/objcgenerator.cs

So we need to remove our own call, which overwrites the original one.

[objc] `mono_embeddinator_create_object` now calls `mono_gchandle_new`

---

objcgen/objcgenerator.cs
tests/managed/exceptions.cs
tests/managed/managed.csproj
tests/managed/methods.cs
tests/objc-cli/libmanaged/Tests/Tests.m

It's similar to XI/XM NSObjectFlag - we need a different road to call
the base classes without calling managed code twice (e.g. the Super
and Base tests for exceptions).
Note: `init` is not always exposed, so we cannot trust it blindly.
This allow the same "internal" `initWithSuper` to be re-used to return
instance of types being bound (e.g. a `+create` without a `-init`).

[objc] Fix subclassing when `init` is not available

---

objcgen/objcgenerator.cs

- Don't expose `MonoEmbedObject* _object;` in the public headers - it's
not meant to be used outside the generated code (but make it @public);
- Don't expose `dealloc` in the headers - it's not meant to be called
from public code;
- Call `__initialize_mono` when loading assembly image, not class - the
later happens way more often;
- Drop `__lookup_class_*` functions in favor of `+initialize`;
- That makes it possible to remove the `__lookup_class_*` call from methods;

[objc] Remove non-public information from header files and simplify runtime initialization

---

README.md
objcgen/README.md

objcgen.exe has to be used in order to try the new generator (with the latest fixes).

[objc][README] Recommend usage of objcgen.exe instead of MonoEmbeddinator4000.exe

---

support/mono_embeddinator.c

Use _NSGetExecutablePath instead of proc_pidpath to get the executable path,
because the latter doesn't exist on iOS.

[objc] Use _NSGetExecutablePath instead of proc_pidpath to get the executable path.

---

objcgen/driver.cs
objcgen/objcgenerator.cs
support/mono_embeddinator.c
tests/objc-cli/.gitignore
tests/objc-cli/Makefile

This also:
* Fixes the -o support (by actually using the output directory)
* Revert the change to make the `_object` private (in the implementation
only), because this doesn't compile when building for the legacy Objective-C
runtime (32-bit macOS).

[objc] Add support fat and static libraries for all platforms.

---

support/mono_embeddinator.c

The `path` variable is accessed later than first thought when an error occurs,
so we need to make sure to only free it after all uses are done.

[objc] Fix use-after-free by freeing after use.

---

objcgen/objcgenerator.cs
tests/objcgentest/ObjCGeneratorTest.cs

The convention is that there's a space between the type and the pointer character (*) in Objective-C.
See: https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html#//apple_ref/doc/uid/20001282-BCIGIJJF
_Note: Apple's frameworks are using this convention too._

[objc][generator] Update type/pointer spacing to follow ObjC conventions

---

objcgen/objcgenerator.cs

We currently disable the `init` ctor when is not needed i.e. static
classes in .NET but we should also disable the `new` static selector
since you could do `[foo new]` and get an instance.

[objc] Disable the `new` selector when no `init` is available

---

objcgen/objcgenerator.cs
tests/managed/methods.cs
tests/objc-cli/libmanaged/Tests/Tests.m

* Better name for setter only properties, e.g.
-       [query set_Secret: 1];
+       [query setSecret: 1];
* Second method argument should be lowercased, e.g. `second`
[Methods_Parameters concatFirst:@"first" second:@"second"]
* Reduce some code duplication, to avoid fixing things multiple times, e.g.
* Unify the signatures generation for ObjC and Mono;
* Unify the parameter marshaling code (the one for methods was missing a lot)
* Simplify `ImplementMethod` arguments

[objc][generator] Produce better names for ObjC methods

---

objcgen/Makefile
tests/managed/Makefile
tests/objc-cli/Makefile

This prevents fleeting visions of red text in the terminal.

[objc] Use msbuild instead of xbuild.

---

objcgen/objcgen.csproj
objcgen/objcgenerator.cs
support/embeddinator.h
support/mono_embeddinator.h
tests/objc-cli/.gitignore

This way we can limit the API surface of the generated code.

[objc] Add a header (embeddinator.h) that's meant to be included by generated headers.

---

objcgen/driver.cs
tests/objcgentest/Cache.cs
tests/objcgentest/DriverTest.cs
tests/objcgentest/objcgentest.csproj

This makes it easier to test, because Driver.Main can be called multiple
times, each time independent from previous executions.

[objcgen] Create an embedder class that contains the state required to run the embeddinator.

---

tests/objc-cli/.gitignore
tests/objc-cli/Makefile
tests/objc-cli/libmanaged/libmanaged.xcodeproj/project.pbxproj

This cleans up the current directory quite a bit.
Also modify the cli/perf tests a little bit to be able to run the
debug/release versions in parallel.

[tests][objc] Build debug tests into a subdirectory as well.

---

docs/ObjC.md
objcgen/objcgen.csproj
objcgen/objcgenerator-helpers.cs
objcgen/objcgenerator.cs
tests/objc-cli/libmanaged/Tests/Tests.m

.NET .ctor are not inherited but `init*` methods are in ObjC, we now
mark as `NS_UNAVAILABLE` the ctors that are not available.
Also this commit introduces `objcgenerator-helpers.cs` which its main
intention is to move the small ObjC related functions like
`GetObjCConstructorName` or `GetUnavailableParentCtors` to avoid
polluting `objcgenerator.cs`
```
Testing failed:
'initWithId:' is unavailable
```
Will fix/remove the assert once bot confirms, I am still not sure how to properly test a `NS_UNAVAILABLE` feature in XCT ...

[objc] Avoid objc ctor inheritance. Fixes issue #72

---

objcgen/objcgenerator.cs
tests/managed/structs.cs
tests/objc-cli/libmanaged/Tests/Tests.m

Remove the `op_` prefix on operators.
Also fix a (non fatal) typo, extra `)`, when computing mono signatures.

[objc] Generate better looking names for operators

---

objcgen/objcgenerator.cs
tests/managed/methods.cs
tests/objc-cli/libmanaged/Tests/Tests.m

As Alex pointed out this scenario requires the `_object` field to be
public.

[objc] Fix the case where bound type A creates instance of bound type B

---

objcgen/objcgenerator-processor.cs
objcgen/objcgenerator.cs
tests/managed/methods.cs
tests/objc-cli/libmanaged/Tests/Tests.m

That's basic support. The nicer way would be to use subscripts [1]
[1] https://github.com/mono/Embeddinator-4000/issues/122

[objc] Generated (property) indexers as methods

---

docs/error.md
objcgen/objcgenerator-processor.cs

Right now this is ignored [1] so we warn about them.
[1] https://github.com/mono/Embeddinator-4000/issues/73

[objc] Warn if default values are used on parameters

---

support/mono_embeddinator.c

A ConfigurationErrorsException was raised when trying to use WebClient/HttpClient
right now we are setting mono_domain_set_config's base_dir to current working
directory and giving it a non existent app config. We might want to adjust
this settings in the future when needed.
Ref: https://github.com/mono/mono/commit/57f5187ad29a7913f083a659ea77d90eb8bad4d4

[objc] Add call to mono_domain_set_config to avoid ConfigurationErrorsException

---

objcgen/objcgenerator-processor.cs
objcgen/objcgenerator.cs
tests/managed/structs.cs
tests/objc-cli/libmanaged/Tests/Tests.m

We cannot access them directly but we can provide (ObjC) property
wrappers around them, making them usable from ObjC code.

[objc] Add basic (readonly) support for fields

---

tests/objc-cli/libmanaged/Tests/Tests.m

Otherwise we might not be able to call methods, because clang will look for any matching selector in any type it knows about, which results compiler errors like:
```
In module 'XCTest' imported from /work/Embeddinator-4000/tests/objc-cli/libmanaged/Tests/Tests.m:1:
In module 'UIKit' imported from /Applications/Xcode83.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks/XCTest.framework/Headers/XCUIElement.h:8:
/Applications/Xcode83.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAccelerometer.h:24:51: note: one possibility
@property(nonatomic,readonly) UIAccelerationValue x;
^
In file included from …
```

[tests][objc] Make sure variables are declared with the right type.

---

objcgen/objcgenerator.cs

Adding `readwrite` to objective-c properties adds no value since it
is the default setting.
Removal was suggested in https://github.com/mono/Embeddinator-4000/pull/129#issuecomment-294491293

[objc] Removes `readwrite` in objc properties since it is the default

---

objcgen/objcgenerator.cs
tests/managed/methods.cs
tests/objc-cli/libmanaged/Tests/Tests.m

The managed API could return `null` even if no exception occurred so we tried to create an object with `mono_embeddinator_create_object (__result);` and 💥  so we check now if `__result` is `null` and return `nil` instead.

[objc] Check if __result is not null to create an object

---

docs/error.md
objcgen/objcgen.csproj
objcgen/objcgenerator-processor.cs
objcgen/objcgenerator-subscripts.cs
objcgen/objcgenerator.cs
tests/managed/.gitignore
tests/managed/CustomBuildActions.targets
tests/managed/managed.csproj
tests/managed/properties.cs
tests/managed/subscripts.tt
tests/objc-cli/libmanaged/Tests/Tests.m

#122
- For indexed properties with integral input types, we can expose those via "Indexed Subscripting":
(id)objectAtIndexedSubscript:(*IndexType*)idx;
(void)setObject:(id)obj atIndexedSubscript:(*IndexType*)idx;
- For the rest we can use "Keyed Subscripting":
(id)objectForKeyedSubscript:(*KeyType*)key;
(void)setObject:(id)obj forKeyedSubscript:(*KeyType*)key;

Implement Indexed and Keyed Subscripting

---

objcgen/comparablehelper.cs
objcgen/extensions.cs
objcgen/methodhelper.cs
objcgen/objcgen.csproj
objcgen/objcgenerator-processor.cs
objcgen/objcgenerator.cs
support/objc-support.h
support/objc-support.m
tests/managed/icomparable.cs
tests/managed/managed.csproj
tests/objc-cli/libmanaged/Tests/Tests.m
tests/objcgentest/ExtensionsTest.cs

We cannot support the _normal_ `IComparable` signature
> Int32 CompareTo(System.Object)
because `System.Object` is not `NSObject`. It's also not the pattern used
in Apple frameworks.'
But we can easily match it to the common (Foundation) signature
> - (NSComparisonResult)compare:(NSSomething *)other;
Part of the fix for:
https://github.com/mono/Embeddinator-4000/issues/124

[objc] Add support for non-generic `IComparable` interface

---

objcgen/comparablehelper.cs
objcgen/objcgenerator-processor.cs
objcgen/objcgenerator.cs
tests/managed/icomparable.cs
tests/objc-cli/libmanaged/Tests/Tests.m

This gets priority over the `IComparable` implementation, using
`System.Object`, if present.
We let the normal generation cover cses of `IComparable<T>` when `T` is
not the declaring type. E.g.
> public class X : IComparable<Y>, IComparable<Z> {}

[objc] Add support for `IComparable<T>`

---

docs/Limitations.md
objcgen/objcgenerator.cs
tests/objc-cli/libmanaged/Tests/Tests.m

In general we don't encourage `null` since it's likely to get managed
`ArgumentNullException` which cannot be well handled on the ObjC side.
That's covered by:
> NS_ASSUME_NONNULL_BEGIN
Right now we lack any metadata to make this more precise :-(. However,
when possible, we can put specific annotations on some API, e.g.
1. Any managed exception in a `.ctor` (or the `.cctor`) will make the
corresponding `init*` method return `nil`, so we always mark them as
`nullable`.
2. `ref` and `out` on reference types can be `nullable`

[objc] Fix clang warnings about nullability

---

objcgen/objcgenerator-postprocessor.cs
objcgen/objcgenerator.cs
objcgen/processedtypes.cs

- https://github.com/mono/Embeddinator-4000/issues/174
- No test needed as fails exisitng test if op name change code is commented out
- Once we move more logic into the ProcessedMethod we can likely push it down into ImplementMethod

Move operation naming code into post processing

---

docs/error.md
objcgen/driver.cs
objcgen/extensions.cs
objcgen/generator.cs
objcgen/methodhelper.cs
objcgen/objcgenerator-helpers.cs
objcgen/objcgenerator-processor.cs
objcgen/objcgenerator.cs
objcgen/processedtypes.cs
tests/objcgentest/EmbedderTest.cs
tests/objcgentest/ObjCGeneratorTest.cs
tests/objcgentest/StringExtensionsTest.cs
tests/objcgentest/TypeExtensionsTest.cs
tests/objcgentest/objcgentest.csproj

* Detect any duplication based on the assembly (internal) name and also
it's sanitized (safe) name. Otherwise generated code won't work;
* Avoid recomputing the name (or safe name) whenever possible;
* Adjust unit tests for some code movement that ease reuse;

[objc] Add ProcessedAssembly and uniqueness validation

---

objcgen/EqualsHelper.cs
objcgen/HashHelper.cs
objcgen/objcgenerator.cs

* Move constants from the caller into the helper code;
* Specify that the argument (id) to isEqual can be null (`_Nullable`);

[objc] Do not require setting constants values to use [Equals|Hash]Helper

---

objcgen/classhelper.cs
objcgen/methodhelper.cs
objcgen/objcgen.csproj
objcgen/objcgenerator-processor.cs
objcgen/objcgenerator.cs
objcgen/protocolhelper.cs
tests/managed/interfaces.cs
tests/managed/managed.csproj
tests/objc-cli/libmanaged/Tests/Tests.m

This allow an .NET API to return an interface. That interface is defined
as a protocol in ObjC.
We also supply an internal `__*Wrapper` class so ObjC can call the
interface members.
Also fix virtual calls - the current code was calling the interface
itself, not the implementation for it.
Note: it's basic in the sense that it does not allow .NET to call back
into ObjC code (that conforms to the protocol).

[objc] Add basic interface/protocol support

---

objcgen/objcgenerator-helpers.cs

Fixes https://github.com/mono/Embeddinator-4000/issues/196

[objc] Remove space between type declaration and argument

---

objcgen/objcgenerator.cs
tests/objc-cli/libmanaged/Tests/Tests.m

This happens if there's no initialization. Previously the lack of a
public `.ctor()` meant we did not generate the code (nothing to call).
This was not correct (since it's valid in .net) so we detect the
condition and generate a simpler `init` method in such case.
Unit tests added (for the existing `Point` type that suffered, unnoticed,
from this)
Fix https://github.com/mono/Embeddinator-4000/issues/202

[objc] Support ValueType with no default constructor

---

objcgen/methodhelper.cs
support/mono-support.h

Right now exceptions from `init*` are ignored and returns null, so no
half backed instance is returned to native code.
This will actually print the _ignored_ exception so a debugger is not
needed to report what went wrong with those calls.
E.g. from Xcode unit tests
2017-04-28 10:01:45.409171-0400 xctest[92173:48871203] System.NotFiniteNumberException: Number encountered was not a finite quantity.
at Exceptions.Throwers..ctor () [0x00008] in <ad2101828b344b3fb1eff45170e0bcb4>:0
2017-04-28 10:01:45.412577-0400 xctest[92173:48871203] System.TypeInitializationException: The type initializer for 'Exceptions.ThrowInStaticCtor' threw an exception. ---> System.Exception: Exception of type 'System.Exception' was thrown.
at Exceptions.ThrowInStaticCtor..cctor () [0x00001] in …

[objc] Print (NSLog) any managed exceptions that we are ignoring

---

objcgen/objcgenerator-subscripts.cs

From:
`- (void)setObject:(id)obj atIndexedSubscript: (int)idx;`
To:
`- (void)setObject:(id)obj atIndexedSubscript:(int)idx;`

[objc] Fix generated indexed subscripting spacing

---

objcgen/EqualsHelper.cs
objcgen/classhelper.cs
objcgen/objcgenerator-helpers.cs
objcgen/objcgenerator.cs
support/objc-support.h
support/objc-support.m
tests/managed/interfaces.cs
tests/objc-cli/libmanaged/Tests/Tests.m

and add unit tests. This required a few other changes like:
* Getting the managed instance, if it exists, from a native instance is
moved to the support code (so it can be shared for multiple usages);
* Most (unless static) bound types now expose `xamarinGetGCHandle`, i.e.
not just the one where `isEqual:` is implemented);
* `xamarinGetGCHandle` exists only inside the implementation (.m), not
in the header (.h) file and is commented to be for internal uses only;
* EqualsHelper is modified to reuse the shared code;

[objc] Correctly expose types that conforms to (bound) protocols

---

objcgen/objcgenerator.cs

When coding, people attach the pointer char to either the type or the variable but the convention is to attach it to the variable.
See first example in https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingIvarsAndTypes.html#//apple_ref/doc/uid/20001284-BAJGIIJE
Also all properties in the iOS framework are following this convention.
You never see `NSString * myName`.

[objc] Attach pointer char '*' to variable for properties

---

objcgen/objcgenerator-processor.cs

reference: https://github.com/mono/Embeddinator-4000/issues/189
We prefer to warn and skip generation of known missing features
rather than throw an error that blocks testing existing assemblies

[objc] Warn that arrays are not yet supported

---

objcgen/operatoroverloads.cs
tests/managed/overloads.cs

- https://github.com/mono/Embeddinator-4000/commit/c36d639770f86ca5602e52aceddf5d6417ef0514 removed need for exception but it was not removed
- Fixes https://github.com/mono/Embeddinator-4000/issues/207 from operator issues. Now hitting:
error EM0009: The feature `Returning type Nullable`1 from native code` is not currently supported by the tool

Allow many operator overloads

---

objcgen/objcgenerator-processor.cs
tests/managed/methods.cs

Solve:
```
Generating binding code...
error EM0009: The feature `Returning type Nullable`1 from native code` is not currently supported by the tool
```
when a nullable type (not yet supported [1]) was used in extensions
methods.
[1] https://github.com/mono/Embeddinator-4000/issues/229

[objc] Move the processing of extension methods after we check for unsupported types

---

objcgen/objcgenerator-processor.cs

Warning is better (now) as it let the processing and generation continue
further, i.e. it just skip what it can't process.

[objc] Warn if trying to process unsafe code (pointers) or the `DBNull` type

---

objcgen/objcgenerator-processor.cs
tests/managed/types.cs

In such case a warning will be displayed and nothing will be generated.
Test added so we can ensure such condition does not stop the generation
with an error.

[objc] Skip generation for subclasses of unsupported types

---

docs/error.md
objcgen/objcgenerator-processor.cs
tests/managed/methods.cs
tests/objc-cli/libmanaged/Tests/Tests.m

Creating categories on primitive types is not possible with ObjC.
Instead just create a _normal_ static method so the API can still be
used.
https://github.com/mono/Embeddinator-4000/issues/249

[objc] Do not create categories for extension methods on primitive types. Fix issue #249

---

samples/Makefile
samples/UnitsNet/.gitignore
samples/UnitsNet/Makefile
samples/UnitsNet/README.md

There is a large number of warnings (for things we don't yet support) but
both the generation (to ObjC) and compiling (with clang) should succeed
and produce a fat (i386/x86_64) .dylib that can be used for macOS apps

[objc][samples] Add Makefile to download UnitsNet nuget and create a native macOS dylib for the library

---

objcgen/NameGenerator.cs
objcgen/objcgenerator.cs

Spinoff of PR #251 [1], which goal is postponed for a bit, to fix issues
found while implementing support for mscorlib types.
* mono signatures for interfaces != `object`;
* we should only generate class handles for extension types part of the
current assembly;
* if a method is final (sealed) then it's not really virtual
Sadly the original test cases cannot be applied :(
[1] https://github.com/mono/Embeddinator-4000/pull/251

[objc] Fix issues found while working on issue #176

---

objcgen/NameGenerator.cs
objcgen/extensions.cs
objcgen/objcgenerator-processor.cs
objcgen/objcgenerator.cs
objcgen/processedtypes.cs

Use queues for assemblies and types so it's possible to add some while
processing them, e.g.
* adding code from another assembly, e.g. TimeSpan from mscorlib;
* adding new types, e.g. extensions methods creates one (or many)
categories;
Start reducing the field sharing between the processor and the
generator. Both should, ideally, split off completely (but that
will require a few more PR)

[objc] Ease the addition of assemblies and types while processing code

---

objcgen/driver.cs
support/mono-support.h
tests/objc-cli/Makefile

Embedding with Xamarin.iOS is different than doing it directly with mono.
This requires some methods to be defined, like the ones only used for
release (when `TOKENLOOKUP` is defined).
The integration with mtouch is also incomplete (for non-debug build) as
some steps (MdbSym) and SymbolStrip (only used in release by default)
causes FileNotFoundException (some state is not set correctly).
This PR is a fix for the former (headers), a workaround for the later
(mtouch invocation) and a Makefile change to make sure we always build
release/iOS on bots (because untested stuff never works, for long)
ref: https://github.com/mono/Embeddinator-4000/issues/237

[objc] Make sure we can build for iOS release using mtouch. Partial fix for #237

---

objcgen/EqualsHelper.cs
objcgen/HashHelper.cs
objcgen/methodhelper.cs
objcgen/protocolhelper.cs

The comments covers `NSObject` protocol support for
* `- (bool)isEqual:(id _Nullable)other;`
* `- (NSUInteger)hash;`
and all `@protocol` where we link to the subclassing limitation.

[objc] Add more generated comments in headers

---

tests/objc-cli/libmanaged/Tests/Tests.m

warning: initialization of pointer of type 'id _Nonnull' to null from a
constant boolean expression [-Wbool-conversion]

[objc][tests] Fix testObjectIndexedSubscripting boolCollection test

---

docs/getting-started-objc-ios.md
docs/getting-started-objc-macos.md
docs/getting-started-objective-c.md
objcgen/Makefile

This embeddinator-4000-commands file has a path to the e4k command folder
which includes the objcgen command.
Fixes issue 277: [Package] Add Library/Frameworks/Xamarin.Embeddinator-4000.framework/Commands to $PATH
(https://github.com/mono/Embeddinator-4000/issues/277)

[package/installer] Touch etc/paths.d/embeddinator-4000-commands

---

objcgen/driver.cs
tests/objcgentest/DriverTest.cs

- drop all single arguments for compilation target (--dll, --shared, --static).
- use the right value names for --target.

[objc] Update command line options for compilation target

---

objcgen/driver.cs

This makes sure that we can print the original stack trace, which makes
finding out what wasn't implemented easier.

[objcgen] Capture the inner exception for handled NotImplementedExceptions.

---

objcgen/driver.cs

Avoids this warning:
> warning MT0030: The executable name (managed-ios) and the app name (appdir) are different, this may prevent crash logs from getting symbolicated properly.

[objc] Name the output directory for iOS to match the binary to avoid an mtouch warning.

---

objcgen/Make.config
objcgen/driver.cs

[objc] Xamarin.iOS now supports stripping when in embeddinator mode.

---

objcgen/driver.cs

The linker can re-save assemblies that aren't linked, which may change
metadata tokens.
So we need to disable metadata token lookup when linking.
See also https://github.com/mono/Embeddinator-4000/issues/304

[objc] Disable metadata token lookup when using the linker.

---

objcgen/objcgenerator.cs
support/mono_embeddinator.c
support/mono_embeddinator.h
support/objc-support.h
support/objc-support.m

Remove the assembly search hook that returns the path of an assembly, and
instead have an assembly load hook, which returns an already loaded
MonoAssembly *.
This makes writing the hook a bit simpler, because string-returning hooks need
specific memory management (a hook that returns a `const char *` won't be able
to use dynamically allocated strings easily, and returning a `char *` runs
into questions about how to free that string). It's much simpler to just
return a MonoAssembly*, which mono must free when unloaded.

[objc] Add an assembly load hook, and use it to find assemblies in bundles.

---

objcgen/processor.cs

also don't create an additional `ProcessedAssembly` instance when adding
extraneous types

[objc][processor] Set the 'end' state when all (not any) assemblies are processed

---

objcgen/NameGenerator.cs
objcgen/objcgenerator-helpers.cs
tests/managed/overloads.cs

reference:
https://github.com/mono/Embeddinator-4000/issues/309

[objc] Hide `[]` and `&` when we use type names as parameter names to avoid duplicates on overloads. Fixes #309

---

objcgen/NameGenerator.cs
objcgen/objcgenerator-helpers.cs
tests/objc-cli/libmanaged/Tests/Tests.m

Fixes issue 194: [objc] Use word "Value" in method's names after a type
(https://github.com/mono/Embeddinator-4000/issues/194)
- We now have nice names when using types in methods names (no more Int16, Int32, Int64...)
and they use the word 'Value' at the end which is standard in Objective-C.
See: https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html#//apple_ref/doc/uid/20001282-BCIGIJJF
The method's argument description also use the new friendly names which is better since it matches the Objective-C types and the argument's names.
- Use camel case for method's argument description so we have `findFirstName: lastName:`.
- Fixed up tests accordingly.

[objc] Use word 'Value' after type name in methods name

---

tests/objcgentest/Asserts.cs

In my case this made it a lot faster to realize tests were failing because of
outdated dependencies.

[objc][tests] Show error message if error code assert fails.

---

objcgen/driver.cs
objcgen/objcgen.csproj
objcgen/objcprocessor.cs
objcgen/processedtypes.cs
support/linker.xml
tests/managed/types.cs
tests/objc-cli/libmanaged/Tests/Tests.m

This replace the older (not linker friendly) PR #251.
It brings, if required, `System.TimeSpan` inside your projects since
there is direct, good alternative, i.e. `NSTimeInterval` is just a
typedef on `double`.

[objc] Add support for System.TimeSpan into generated projects

---

docs/errors.md
docs/releases/Embeddinator-4000_0.2.md
objcgen/driver.cs
samples/UnitsNet/Makefile
tests/objcgentest/ObjCGenErrWarnTests.cs

Code was already present (copied from mtouch/mmp with ErrorHelper.cs) so
it's an easy and useful thing to expose.
Use `--nowarn` on UnitsNet sample to reduce the warnings that we cannot
fix (since we're using a binary downloaded from nuget)
Add unit tests for `--nowarn`. The one for `--warnaserror` did not work,
at least inside VSfM, due to bug #55801, resulting in:
> mono_os_mutex_lock: pthread_mutex_lock failed with "Invalid argument" (22)

[objc] Add `--nowarn:` and `--warnaserror:` options to the driver

---

objcgen/objcgenerator-postprocessor.cs
objcgen/objcgenerator.cs
objcgen/objcprocessor.cs
objcgen/processedtypes.cs

- Make ComputeSignatures an internal idea, triggered by property changes that invalidate signature

More cleanup and improvements enabled by signature move

---

objcgen/HashHelper.cs
objcgen/generator.cs
objcgen/objcgenerator-postprocessor.cs
objcgen/objcgenerator.cs
objcgen/objcprocessor.cs
objcgen/operatoroverloads.cs
objcgen/processedtypes.cs

One of many cases to cover. The move helps in many ways, including
making sure the `hash` method addition is done before dupe names are
processed (e.g. a .net method/property could be named `Hash`)

[objc] Move `hash` support to the processor

---

binder/CLI.cs

- You can specify `--gen` multiple times at the command line
- `--gen=Java` will automatically imply `--gen=C` first
- I don't think this breaks any command line argument validation
@tritao does it need to assume C if you leave `--gen` off completely? This would print `Please specify a target generator.`, but I think that is probably right.

CLI - support for multiple generators

---

objcgen/objcgenerator.cs
objcgen/processedtypes.cs

- https://github.com/mono/Embeddinator-4000/issues/365
- Also move cache to not be generated until first use, not at construct time. This should cut down on the number of "stale" cached signatures.
- Modifying types after requesting signatures will currently give you stale data. No easy way beyond wiring all properties to invalidate or adding a manual invalidate.
- Clean up GenerateDefaultValuesWrapper to use more bits from central base type instead of null checking two copies.

Refactor GetObjcSignature / GetMonoSignature to be private and always use cache

---

objcgen/CachedValue.cs
objcgen/objcgen.csproj
objcgen/objcgenerator-postprocessor.cs
objcgen/objcgenerator.cs
objcgen/objcprocessor.cs
objcgen/processedtypes.cs

- ImplementMethod now only takes one argument
- Remove Invalidation hack - https://github.com/mono/Embeddinator-4000/issues/370
- Semi implement freezing. We now only cache after freezing. Later we can look at improved permissions or exceptions - https://github.com/mono/Embeddinator-4000/issues/371

Improve ImplementMethod, remove invalidation, and cache freezing

---

binder/Compilation.cs
support/java/Runtime.java
support/java/RuntimeException.java
tests/common/Makefile

The changes here I discussed with @tritao, these are mainly to get desktop Java in a working state.
- On MacOS, `darwin/libX.dylib` is packaged up in the jar file
- .NET assemblies are packaged into `/assemblies/` inside the jar file
- *For now*, `Runtime.java` extracts the assemblies to a temp directory for use. We should investigate if the runtime can load them directly from the jar.
You can find the sample I used to test [here](https://github.com/jonathanpeppers/Embeddinated-Android/blob/master/lib-java/src/main/java/com/xamarin/Main.java).

Java - jar files are now usable within a Java project on MacOS

---

binder/Compilation.cs
build/projects/MonoEmbeddinator4000.csproj
tests/common/Makefile

- We don’t want developers to have to pull jna-4.4.0.jar into their
project
- This unzips it into our jar, so they just have to worry about a
single file
- Updated tests, so it is not using the jar from /external/jna

[java] - embed JNA into our jar file

---

binder/Compilation.cs
support/java/Runtime.java
support/mono_embeddinator.c

- After a lot of research, I discovered that JNA actually extracts
native libraries from jar files into a temporary directory [see here](https://github.com/java-native-access/jna/blob/master/src/com/sun/jna/Native.java#L998)
- This makes it seem reasonable that we are doing the same with .NET
assemblies
- One improvement I saw from their implementation that could improve
ours: don’t use `File.exists()` and use `File.deleteOnExit()`
- This should extract/delete .NET assemblies on every run the same way
that JNA handles native libraries
- Turns out that desktop Java was loading `mscorlib.dll` from current
machine’s Mono installation
- Now we package mono assemblies into jar file
- Same logic is used for calling `mono_set_dirs` as Android

[java] improvements for Java on MacOS

---

binder/Compilation.cs

Handles failures for:
- C compilation for Windows, Mac, and Android NDK
- Jar/Aar file creation
This fixes the case where if you use `--generator=Java --compile` and C compilation fails, it does not continue on with the Java generator/compiler.
Embeddinator will print this instead:
```
Compiling binding code...
Failed to compile generated code.
```

[driver] handle exit codes for C compilation & Java packaging

---

binder/Compilation.cs

This used to not work, but since we switched to using the prebuilt Android NDK toolchains it seems to work now
So now we get in the AAR:
```
adding: jni/arm64-v8a/libmanaged.so(in = 310832) (out= 70309)(deflated 77%)
```
@tritao try this on your phone with the Android tests you are working on, and let me know

[android] enable arm64-v8a

---

binder/Compilation.cs
binder/Generators/C/CGenerator.cs
binder/Generators/Java/JavaGenerator.cs
binder/Generators/Java/JavaNative.cs
binder/premake5.lua

- When writing docs for Java/Android, I used the .NET example from the
ObjC side.
- Apparently an assembly named `hello-from-csharp` breaks things

[c] [java] Fixes for hyphens in assembly names

---

binder/Compilation.cs
support/java/Runtime.java
support/java/RuntimeException.java

- This fixes a lot of the warnings printed when running `—gen=Java`
- For Java 1.7 support, use `-bootclasspath`. Needs to point at
`rt.jar` on desktop and `android.jar` on Android
- `Runtime.java` should use proper `List<String>` return type on
`getFieldOrder()`
- `RuntimeException.java` is implementing a ctor that does not exist in
Java 1.7

[java] fix various warnings

---

.gitmodules
binder/Compilation.cs
binder/Utils/NdkUtils.cs
docs/getting-started-java-android.md
docs/getting-started-java.md
tests/managed/CustomBuildActions.targets

This gets the following command working on Windows:
```
MonoEmbeddinator4000.exe -gen=Java -c -platform=Android -o test ..\..\..\tests\managed\generic\bin\Debug\managed.dll
```
Here is a list of the things I had to change:
- Include `nuget.exe` for Windows
- Show an error if `JAVA_HOME` is blank
- Hook up `AndroidLogger.Warning` event
- Fix for `bootclasspath` if it contains spaces
- MonoDroid location is slightly different on Windows
- Use `Path.Combine` for mono includes in `CompileNDK`
- Use `exe` suffix for gcc in `NdkUtils`
- Started updating docs for Android/Windows
- Fixed `CustomBuildAction.targets`, Fixes #337 
Don't merge this quite yet, but comment if I need to fix anything. I need one more change in externals/Xamarin.Android.Tools for VS 2017 and I will talk to Dean about it …

[android] support for generating AARs on Windows

---

generator.sln
tests/android/Makefile
tests/common/Shared.make
tests/managed/exceptions.cs
tests/managed/interfaces.cs
tests/managed/pcl/managed-pcl.csproj
tests/managed/properties.cs

- Added a general test project for testing PCLs
- Only had to create a couple `#if` to support PCL
- Made `pcl-compile` and `pcl-run` make targets
This doesn't fix anything, but adds a test project for #407 
I investigated if #407 could be fixed without Xamarin.Android, but facade assemblies would need to be extracted along with `mscorlib.dll`. I will continue work on Xamarin.Android integration to fix this issue.

[tests] added PCL project

---

binder/Generators/C/CHeaders.cs
binder/Passes/GenerateArrayTypes.cs
support/c-support.h
support/embeddinator.h
support/mono-support.h
support/mono_embeddinator.h

This gives us cross-assembly array generation support aswell as leading to less duplicated code due to shared primitive array defintions.

[c] Rework array generation in C

---

.cake/packages.config
.gitignore
.gitmodules
build.cake
build.ps1
build.sh
docs/Contributing.md
tools/packages.config

Our various `Makefiles` do not currently work well on windows, so @tritao and I are looking to start the process of migrating to Cake.
This PR includes:
- Just a few build targets `Generate-Android` is set to `Default`
- `Run-Java-Tests` works (except on Windows there is an issue compiling C)
- Windows & OS X bootstrap scripts for Cake
- Point `external/Xamarin.Android.Tools` back to official repo
Changes from standard Cake scripts:
- Using experimental flag for C# 6/Roslyn on Windows
- Using `.cake` instead of the `tools` directory
- Using `.nuget/nuget.exe` because we already have it there
From here, we can start adding more Cake tasks.

Cake build scripts

---

support/java/android/AndroidImpl.java
support/java/android/MonoPackageManager.java
tests/android/app/src/androidTest/java/mono/embeddinator/AndroidTests.java
tests/managed/android/android.cs

Xamarin.Android has a static property `Application.Context` that calls into a Java `MonoPackageManager` class, see [here](https://github.com/xamarin/xamarin-android/blob/master/src/Mono.Android/Android.App/Application.cs).
We did not have this in Embeddinator, so any of the following would crash:
- Calling `Application.Context` directly
- Using async/await or `System.Threading.Tasks`
- These use the context for synchronizing tasks back on the main thread
I discovered this when working on a sample: https://github.com/jamesmontemagno/embeddinator-weather/pull/3 
To fix this, I made a stub of `MonoPackageManager` in Embeddinator with a single field. Xamarin.Android's [version](https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Resources/MonoPackageManager.j …

[android] fix for Application.Context

---

support/java/android/AndroidImpl.java
tests/common/java/mono/embeddinator/Tests.java
tests/managed/types.cs

In Xamarin.Android’s MonoPackageManager, there is some logic around
timezone changes we did not have setup in Embeddinator:
https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Resources/MonoPackageManager.java#L29
I added a test case for `DateTime.Now` as a smoke test, but I think
this change only affects the case where a timezone changes on the
device while the application is running. 
I could not find a test in Xamarin.Android checking timezone changes.

[android] setup NotifyTimeZoneChanges class

---

binder/Compilation.cs
binder/Utils/XamarinAndroid.cs
binder/Utils/XamarinAndroidBuild.cs
tests/MonoEmbeddinator4000.Tests/XamarinAndroidTest.cs

- Moved API level selection to `XamarinAndroid` class
- `CompileNDK` now works off the highest API level available instead of
hardcoding 24
- added some tests

[android] better selection of Android API level

---

.gitignore
binder/Compilation.cs
binder/Driver.cs
binder/Generators/AstGenerator.cs
binder/Utils/XamarinAndroid.cs
binder/Utils/XamarinAndroidBuild.cs
build.cake
docs/getting-started-java-android.md
docs/getting-started-java.md
tests/android/.idea/misc.xml
tests/android/app/build.gradle
tests/android/app/src/androidTest/java/mono/embeddinator/AndroidTests.java
tests/managed/android/android.cs
tests/managed/android/managed-android.csproj
tests/managed/android/packages.config

If you are embedding an Android library project with a reference to the `Xamarin.Android.Support.v4` NuGet package, for example, the generated Java code did not compile. We need to add any jar files from binding projects to the `classpath` during Java compilation.
- Embeddinator needs to include assembly directories in its search path for `IKVM.Reflection`.
- Java generator will skip over types implementing `IJavaObject` but aren't `Java.Lang.Object`
-  Jars from `library_project_imports` included in `classpath`.
- We are now using `TargetFrameworkVersion` of 7.0 instead of 2.3. This should cover a wider range of C# projects.
- This forces us to use Java 8, since `v7.0/mono.android.jar` is compiled for Java 8. I updated the docs to reflect this.
- I had to rearrange some of the MSBuild …

[android] support for Java binding projects

---

binder/Compilation.cs
binder/Utils/Utils.cs
binder/Utils/XamarinAndroid.cs
tests/MonoEmbeddinator4000.Tests/XamarinAndroidTest.cs

- `Invoke` should probably be moved to `Helpers`
- Let’s do `using static MonoEmbeddinator4000.Helpers` throughout
`Compilation.cs`
- Fixed some string interpolation that could be removed
- `JavaSdkPath` moved to `XamarinAndroid` class
- `JavaSdkPath` is now only calculated once, previously
`/usr/libexec/java_home` would get executed three times for `-gen=Java
-platform=Android`. This also printed the Java path times three times
to the output…

[java] refactoring of Helpers and JavaSdkPath

---

binder/Utils/XamarinAndroidBuild.cs
docs/android-callbacks.md
docs/getting-started-java-android.md
docs/getting-started-java.md
tests/android/.idea/vcs.xml
tests/android/app/src/androidTest/java/mono/embeddinator/AndroidTests.java
tests/managed/android/Java/IJavaCallback.java
tests/managed/android/android.cs
tests/managed/android/managed-android.csproj

- Documented three options for callbacks: abstract classes, interfaces, and virtual methods
- Documented what we can do better in this area
- If a developer uses the `AndroidJavaSource` build action, Embeddinator will now include it to be compiled in the resulting AAR file
- Minor fix for VCS warning in Android Studio project
- Unit tests checking all three scenarios
Fixes #421

[android] callbacks from C# to Java

---

binder/Generators/C/CHeaders.cs
binder/Generators/C/CSources.cs
binder/Generators/Java/JavaSources.cs
tests/MonoEmbeddinator4000.Tests/DriverTest.cs
tests/MonoEmbeddinator4000.Tests/MonoEmbeddinator4000.Tests.csproj
tests/MonoEmbeddinator4000.Tests/Samples/EventArgsEmpty.cs

In testing various libraries, I’ve discovered a subclass of
`System.EventArgs` always breaks the C and Java generators. The
property `EventArgs.Empty` ends up as an `UnsupportedType`, which in
turn prints an empty string for its type.
Skipping these properties is a solution for now, it is at least better
than hitting a C or Java compiler error.
Changes:
- Added integration test that reproduces the issue
- C generator skips `UnsupportedType` for headers & sources
- Java generator skips `UnsupportedType`
Applies to #438

[c] [java] fix for properties of type UnsupportedType

---

binder/Generators/AstGenerator.cs
binder/Generators/Java/JavaMarshal.cs
binder/Passes/GenerateObjectTypes.cs
tests/MonoEmbeddinator4000.Tests/DriverTest.cs
tests/MonoEmbeddinator4000.Tests/MonoEmbeddinator4000.Tests.csproj
tests/MonoEmbeddinator4000.Tests/Samples/Enums.cs

The following were generating invalid C and/or Java:
- C# method with an enum parameter from another assembly
- C# property that is an enum from another assembly
Changes:
- `AstGenerator.ManagedNames` should include enums
- `GenerateObjectTypes` should take parameters & properties into account
- Java - `Enum.fromOrdinal` should use full package name + type name
Applies to #438

[c] [java] fixes for C# enums

---

binder/Generators/AstGenerator.cs
binder/Passes/InterfacesPass.cs
tests/MonoEmbeddinator4000.Tests/DriverTest.cs
tests/MonoEmbeddinator4000.Tests/MonoEmbeddinator4000.Tests.csproj
tests/MonoEmbeddinator4000.Tests/Samples/Interfaces.cs

The following were generating invalid Java:
- C# interfaces extending a base interface
- C# methods that implement an interface explicitly
This broke things like:
- Many libraries have interface inheritance, especially things that extend `IDisposable`
- Xamarin.Forms has explicit interface methods on `VisualElement`, `Element`, and `BindableObject`
Changes:
- `InterfacesPass` needs to loop over any base interfaces
- `InterfacesPass` needs to include a check for `__getObject`, interface inheritance was causing this method to get generated multiple times
- Added `IsExplicitInterfaceMethod` extension method
- `AstGenerator` will now mark explicit interface methods as `public` and fix up the names -- *maybe not exactly ideal* but it works

[java] fixes for C# interfaces

---

build.cake

- Right now for Android, we need to use a Jenkins build of
Xamarin.Android, so we have a Cake task that downloads and unzips
everything in the zip
- This is an improvement to delete unused files so if we make a preview
release, our bundled Xamarin.Android will not be quite so large

[cake] delete unused Xamarin.Android files

---

binder/Driver.cs
binder/Generators/AstGenerator.cs
binder/Passes/RenameDuplicatedDecls.cs
tests/MonoEmbeddinator4000.Tests/Samples/Interfaces.cs

Types of things that would break:
- static field named the same as an explicitly implemented interface member
- static property named the same as an explicitly implemented interface member
Such as:
```csharp
public interface IConflict
{
string TestProperty { get; }
string TestField { get; }
}
public class Conflicted : IConflict
{
string IConflict.TestProperty
{
get { return "IConflict.TestProperty"; }
}
public static string TestProperty
{
get { return "TestProperty"; }
}
string IConflict.TestField
{
get { return "IConflict.TestField"; }
}
public static string TestField = "TestField";
}
```
Changes:
- Reordered passes a bit, so `FieldToGetterSetterPropertyPass` runs after any renaming
- Account for `IsStatic` when checking explicit interfaces in `AstGenerator`
- `RenameDuplicatedDecls` …

[java] [c] improvements to method/field collisions

---

binder/Generators/Java/JavaMarshal.cs
tests/common/java/mono/embeddinator/Tests.java
tests/managed/methods.cs

Managed type parameters like `ref byte val` were generating broken Java code.
These now are supported and generate working code.

[java] Implemented support for marshaling unsigned integer types.

---

binder/Utils/Utils.cs
tests/MonoEmbeddinator4000.Tests/HelpersTests.cs
tests/MonoEmbeddinator4000.Tests/MonoEmbeddinator4000.Tests.csproj

- If distributed through NuGet, Embeddinator has trouble locating the
`external` or `support` directories, because it searches via the
current directory
- `FindDirectory` now searches from the exe path first, then tries the
current directory
- Added some quick “unit” tests

[utils] FindDirectory should also find paths relative to exe

---

binder/Driver.cs

- In testing #468 I found that C was using an older method for finding
the `support` directory
- Removed this in favor of using `Helpers.FindDirectory`

[c] fix for support directory searching

---

binder/Utils/XamarinAndroidBuild.cs

In testing E4K, I found certain projects could cause an exception if
Mono.Cecil needed to load a dependent assembly during
`XamarinAndroidBuild.ProcessAssemblies`.
The fix for this is to use the `DefaultAssemblyResolver` and add a
proper search path.

[android] fix for Mono.Cecil to resolve assemblies

---

binder/Compilation.cs
binder/Utils/XamarinAndroid.cs
tests/MonoEmbeddinator4000.Tests/XamarinAndroidTest.cs

In updating the documentation for Embeddinator-4000, I found that `MSBuild.exe` was not found in `PATH` if trying to run Embeddinator as a post-build event inside Visual Studio.
A little research, and I found it is recommended to lookup the registry key `HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\4.0\MSBuildToolsPath` for finding `MSBuild.exe`.
This fix allows these commands to work inside VS:
```
set E4K_OUTPUT="$(SolutionDir)output"
if exist %E4K_OUTPUT% rmdir /S /Q %E4K_OUTPUT%
"$(SolutionDir)packages\Embeddinator-4000.0.2.0.80\tools\Embeddinator-4000.exe" "$(TargetPath)" --gen=Java --platform=Android --outdir=%E4K_OUTPUT% -c
```

[android] fix for locating MSBuild on Windows

---

build.cake

This is not the only build failure I'm seeing, but this is obviously wrong.

Fix build.cake for Linux. Usually there is no /usr/libexec/hava_home on Linux.

---

binder/Utils/ResourceDesignerGenerator.cs

As there can be more than one Xamarin Android assemblies with resources as e4k input, so make sense to compile resource.designer.cs with all assemblies, not only main one.

[android] reference all assemblies for resource.designer.cs compilation

---

binder/Compilation.cs
binder/Utils/XamarinAndroidBuild.cs

If trying to run Embeddinator on a Xamarin.Forms app, you would have to include `FormsViewGroup.jar` manually to your Android Studio project. This PR enables you to pass `FormsViewGroup.dll` as input to Embeddinator so it will get included in the AAR package.
Changes:
- Look for JAR files from input .NET assemblies
- Refactored to create an `ExtractJar` method, since we do this a lot now
- Found we were including some native libraries from JNA that are not needed on Android. Removing them saved about 600K of file size from the AAR package

[android] improvements to include JAR file dependencies

---

support/mono-support.h

Resolves mono/Embeddinator-4000#478

Prevents mono header imports when targeting iOS/MacOS.

---

support/mono_embeddinator.c

It can be implemented with /proc/self/exe.

[mono_emebddinator.c] Fix get_current_executable_path() on Linux.

---

binder/Generators/AstGenerator.cs
binder/Generators/C/CMarshal.cs
tests/common/Tests.C.cpp
tests/managed/arrays.cs
tests/managed/fsharp-shared/Hello.fs

This enables the generation of methods which use arrays with non-primitive types.
Includes tests for the new feature.

Adding support for class type arrays, fix #496

---

binder/Compilation.cs
binder/Utils/XamarinAndroid.cs
build/projects/CppSharp.Generator.csproj

* We now look up on Windows registry instead of just hoping it is on default location
* We now issue an exception with a proper message in case the SDK is not found

[binder] Improve Mono SDK path lookup on Windows.

---

.gitignore
binder/Compilation.cs
binder/Utils/NdkUtils.cs
binder/Utils/XamarinAndroid.cs
binder/Utils/XamarinAndroidBuild.cs
build/premake5.lua
build/projects/Xamarin.Android.Tools.csproj
external/MonoDroidSdk/MonoDroidSdk.cs
external/MonoDroidSdk/MonoDroidSdkBase.cs
external/MonoDroidSdk/MonoDroidSdkUnix.cs
external/MonoDroidSdk/MonoDroidSdkWindows.cs
tests/MonoEmbeddinator4000.Tests/Approvals/XamarinAndroidBuildTest.AndroidManifest.approved.txt
tests/MonoEmbeddinator4000.Tests/Approvals/XamarinAndroidBuildTest.AndroidManifestWithDots.approved.txt
tests/MonoEmbeddinator4000.Tests/Approvals/XamarinAndroidBuildTest.AndroidManifestWithUpperCase.approved.txt
tests/MonoEmbeddinator4000.Tests/XamarinAndroidTest.cs

[Xamarin.Android.Tools](https://github.com/xamarin/xamarin-android-tools) is going to be shipped in a future version of Xamarin.Android. They've made several API changes up to this point, such as making `AndroidSdk` non-static, improved logging events, and removed `MonoDroidSdk`.
We should keep Embeddinator on the latest Xamarin.Android.Tools, as it has several fixes, and will continue to get fixes as more projects rely on it.
I included the source for the now absent `MonoDroidSdk` in `external/MonoDroidSdk`, as it was used for locating Xamarin.Android.
Other changes:
- `TargetSdkVersion` should be 24 to match "v7.0" - down the road we could add a command line switch for users to specify API level or bump to 26 and "v8.0"
- Added some `.gitignore` for Windows users
- Fixed paths in …

Update Xamarin.Android.Tools to latest

---

docs/getting-started-java-android.md
docs/getting-started-java.md
tests/android/app/build.gradle
tests/android/build.gradle
tests/android/gradle/wrapper/gradle-wrapper.properties
tests/managed/android/managed-android.csproj
tests/managed/android/packages.config

Android Studio 3.0 hit [stable](https://developer.android.com/studio/index.html).
This PR is mainly just updating the docs, our test project, and making sure everything still seems to work. I verified `./build.sh -t Android` works w/ Android Studio 3.0 running the emulator-based tests.
- Updated Android Support libraries from NuGet
- Updated documentation mentioning Android Studio 3.0 as beta

Updates for latest Android Studio 3.0

---

support/java/android/MonoPackageManager.java
tests/android/app/src/androidTest/java/mono/embeddinator/AndroidTests.java

As reported in #530, there are some cases where libraries use
`MonoPackageManager.setContext`, which has a “vestigial”
implementation/comment in Xamarin.Android.
I added this method and a couple quick tests for future validation.

[Android] add MonoPackageManager.setContext

---

binder/CLI.cs
binder/Driver.cs
binder/Generators/C/CGenerator.cs
binder/Generators/C/CHeaders.cs
binder/Generators/C/CMarshal.cs
binder/Generators/C/CSources.cs
binder/Generators/C/CTypes.cs
binder/Generators/Java/JavaMarshal.cs
binder/Generators/Java/JavaTypePrinter.cs
binder/Generators/ObjC/ObjCSources.cs
binder/Options.cs
binder/Passes/GenerateArrayTypes.cs
binder/Passes/GenerateObjectTypes.cs

We need to do this because of Swift's lack of namespaces and global scope operators and it's the only way of disambiguating between C interop types and Swift generated types.

[c/swift] Prefix C generated type names  

---

objcgen/objcgenerator.cs

Properties of an interface type in C# should be id<Protocol> in objective-c.

Fix for issue #405.

---

appveyor.yml
binder/Utils/XamarinAndroidBuild.cs
build/Android.cake
support/java/android/AndroidImpl.java

MSBuild tasks changed a bit:
- Aapt needs to conditionally run if there are no resources
- ResolveLibraryProjectImports had changes to required properties
- Using shorter names for intermediate directories
Other changes:
- Xamarin.Android’s mono.android.Runtime.init had API changes.
- URLs in cake script to download 15-4 build artifact from Jenkins
- AppVeyor cache should watch for `build\Android.cake` changes
After this PR, I'll look at getting API-26 support as the default.

[android] update latest 15-4 stable branch of Xamarin.Android

---

tests/android/app/build.gradle
tests/android/app/src/androidTest/java/mono/embeddinator/AndroidTests.java
tests/android/build.gradle
tests/managed/android/android.cs

- Prompted to update gradle to 3.0.1
- Fixed warnings about deprecated `compile` and `androidTestCompile`
- New test case for #546

[android] latest Android Studio test project updates

---

build/projects/packages.config

When building, build will fail if this package is not present.  Adding a dependency to the package in nuget fixes the issue.
This issue was initially found on macOS High Sierra, Visual Studio for Mac Community Edition

Add required Mono.TextTransform dependency to packages.config

---

build/Tests.cake

Fixes https://github.com/mono/Embeddinator-4000/issues/564.

Do not lookup Java SDK path on global Cake scope.

---

binder/Passes/CheckDeclarationsPass.cs
tests/managed/properties.cs

Fixed generation conflict with properties and methods starting with get/set.
This was a regression caused by https://github.com/mono/Embeddinator-4000/pull/542
Fixes https://github.com/mono/Embeddinator-4000/issues/580.

[java] Fixed generation conflict with properties and methods

---

binder/Utils/ResourceDesignerGenerator.cs
tests/MonoEmbeddinator4000.Tests/Approvals/ResourceDesignerTest.Anim.approved.txt
tests/MonoEmbeddinator4000.Tests/Approvals/ResourceDesignerTest.Full.approved.txt
tests/MonoEmbeddinator4000.Tests/Approvals/ResourceDesignerTest.FullWithResourceFile.approved.txt
tests/MonoEmbeddinator4000.Tests/Approvals/ResourceDesignerTest.String.approved.txt
tests/MonoEmbeddinator4000.Tests/DriverTest.cs
tests/MonoEmbeddinator4000.Tests/MonoEmbeddinator4000.Tests.csproj
tests/MonoEmbeddinator4000.Tests/Samples/mscorlib.cs

Fixes #582
- Added a test case to repro #582
- Improved upon `System.CodeDom` logic, to use more specific type names
via `CodeTypeReference` instead of strings
- no longer need `using System;`
- Improved upon the number of assemblies that `Resource.designer.dll`
references. We only need to reference input assemblies that contain
`Resource` classes generated by Xamarin.Android.
- Updated approval tests to match the new generated code

[android] Improvements to Resource.designer.dll generation

---

objcgen/objcgenerator.cs
tests/managed/types.cs

reference:
https://github.com/mono/Embeddinator-4000/issues/594

[objc] Fix local variable names used for parameter conversion. Fix #594

---

support/java/android/AndroidImpl.java

Manually loading the monosgen-2.0 library to support API < 18

---

build/Tests.cake
tests/managed/fsharp-android/fsharp-android.fsproj
tests/managed/fsharp-generic/fsharp-generic.fsproj
tests/managed/fsharp-generic/packages.config

Test projects failing to build on Linux on TravisCI, perhaps this will
fix it? This seems to be happening since #616, but I think it is a change on
the TravisCI build bots.
Changes:
- FSharp Android project shouldn't have `AndroidUseLatestPlatformSdk` on
- We don't need `System.ValueTuple`
- The `Build-C-Tests` Cake task should also copy `FSharp.Core.dll` as using
the system one doesn't seem to be working reliably on TravisCI

[fsharp] update test projects

---

objcgen/driver.cs

Fixes https://github.com/mono/Embeddinator-4000/issues/534

[objc] Show macos-[modern|full|system] platforms when displaying help. Fix #534

---

tests/managed/netstandard/managed-netstandard.csproj

Relates to #518, but everything appeared to work on my Windows machine

[tests] NetStandard project wasn't referencing shared project

---

tests/objc-cli/libmanaged/Tests/Tests.m

- Almost direct ports (variable names and all)
- Commented out sections are likely either https://github.com/mono/Embeddinator-4000/issues/631 or https://github.com/mono/Embeddinator-4000/issues/630 . I am all but certain they all have the same underlying issue.

Add objc versions of existing C/Java tests that were missed

---

build.cake
build/Tests.cake

We should just use the default verbosity for the MSBuild Cake alias, which follows the verbosity passed to Cake at the command line.
Such as:
./build.sh -v diagnostic
Previously we were always forcing this to `Verbosity.Minimal`.

[build] remove Verbosity passed to MSBuild

---

objcgen/objcgenerator.cs
tests/managed/structs.cs
tests/objc-cli/libmanaged/Tests/Tests.m
tests/objcgentest/xcodetemplate/macos/test/macTests.m

- https://github.com/mono/Embeddinator-4000/issues/636
- https://github.com/mono/Embeddinator-4000/issues/631
- Unlike single structs, which are boxed when we ask for them, arrays
must be handled special.
- We use mono_array_addr_with_size to get a pointer to the specific
element and then mono_value_box to box.
- This was discussed in https://github.com/mono/mono/issues/7808

[ObjC] Correctly marshall arrays of structrs

---

Contributing.md
ProjectStructure.md
README.md
Usage.md
objcgen/Internals.md
tests/Tests.md
tools/diff/README.md

- https://github.com/mono/Embeddinator-4000/issues/160

Add technical documents and improve readme

---

docs/index.html

- Fix broken https://mono.github.io/Embeddinator-4000/ link caused by https://github.com/mono/Embeddinator-4000/commit/0a04d250c968efd4a178ce54362ecb9e068a4b17

Add redirect for github page

---

README.md
docs/errors.md
objcgen/driver.cs
objcgen/embedder.cs
tests/objcgentest/ManagedTest.cs

Looks like some of my previous pull requests are partially missing from latest objc
Ive created this pull request to add back in the partial missing lines for extension support + also enabling of bitcode for iOS
https://github.com/mono/Embeddinator-4000/pull/514
https://github.com/mono/Embeddinator-4000/pull/540

Restored: missing code for extension support on Mac + bitcode for iOS

---

binder/Utils/XamarinAndroid.cs

One of the most common issues Windows developers face when using E4K is a message such as:
Cannot find Java SDK: JAVA_HOME environment variable is not set.
In fact, most Windows users don't set `JAVA_HOME` at all, since it is not something done system-wide by any installer.
Solution? Let's add a fallback to use `AndroidSdk.JavaSdkPath`.
`AndroidSdk` from `xamarin-android-tools` has very reliable logic for finding Java on all platforms. However, we haven't been using it in E4K for locating Java, because it _implicitly_ requires the Android SDK (see class name) be installed in order to work. See where `AndroidSdkInfo` throws here: https://github.com/xamarin/xamarin-android-tools/blob/b159597b15e0f8e302e0aec9efbf7c913d063e33/src/Xamarin.Android.Tools.AndroidSdk/AndroidSdkInfo.cs#L23
Using it …

[java] better logic for finding path to Java

---

.cake/MyGet.config
.cake/packages.config
binder/Utils/XamarinAndroid.cs
build.cake
build.ps1
build.sh
build/Tests.cake
objcgen/Make.config
objcgen/embedder.cs
objcgen/utils.cs
tests/objc-cli/Makefile
tests/objcgentest/EmbedderTest.cs
tests/objcgentest/ManagedTest.cs

Context: https://travis-ci.org/mono/Embeddinator-4000/jobs/471012684
Context: https://travis-ci.org/mono/Embeddinator-4000/jobs/471026456
Context: https://travis-ci.org/mono/Embeddinator-4000/jobs/471037351
First issue we are hitting is a missing version of Cake on MyGet:
Unable to find version '0.23.0' of package 'Cake'.
https://www.myget.org/F/cake/api/v3/index.json: Package 'Cake.0.23.0' is not found on source 'https://www.myget.org/F/cake/api/v3/index.json'.
To fix this:
- Let's remove `MyGet.config` and just use NuGet
- Update Cake to 0.31, I recently used that version on another project
Next issue is that the build will not work using JDK 10:
Compiling binding code...
Invoking: /usr/libexec/java_home
/Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home
Invoking: …

[build] changes to fix the build on Travis CI

---

objcgen/thin-framework.sh

Fixes this warning:
In thin-framework.sh line 70:
let C++ || true
^------^ SC2219: Instead of 'let expr', prefer (( expr )) .
For more information:
https://www.shellcheck.net/wiki/SC2219 -- Instead of 'let expr', prefer (( ...
make: *** [shellcheck] Error 1

[objcgen] Fix shellcheck warning.

---

support/objc-support.m

Fixes https://github.com/mono/Embeddinator-4000/issues/724.

[objcgen] Make sure to mask out any custom flags in the return value from 'xamarinGetGCHandle'. Fixes #724.

---

objcgen/embedder.cs

Xamarin.Mac 4.8 only supports macOS 10.9 (Mavericks) or higher.
fixes https://github.com/mono/Embeddinator-4000/issues/732

[objcgen] fix error MM0073 when building with Xamarin.Mac 4.8 or later

---

azure-pipelines.yml
binder/Compilation.cs
binder/Utils/NdkUtils.cs
build.cake
build.ps1
build.sh
build/Tests.cake
build/Utils.cake
support/mono-support.h

* Setup Azure DevOps for CI
* Install Android NDK Bundle on Windows build agents
* Workaround for `JAVA_HOME` on Windows build agents
* Support for Android NDK r19 and r20
* Updated Cake scripts to support VS 2019 on Windows
* Pin NuGet download URL to v4.7.3
* Bump to xamarin/xamarin-android-tools/master@294f447
* Changes: https://github.com/xamarin/xamarin-android-tools/compare/4c00c22...294f447
* Fix for `mono-support.h` on Windows
Fixes: https://github.com/mono/Embeddinator-4000/issues/716
Fixes:
c:\program files (x86)\mono\include\mono-2.0\mono\utils\mono-publib.h(94): error C2371: 'mono_unichar2': redefinition; different basic types [D:\a\1\s\tests\common\mk\common.Tests.vcxproj]

VS 2019 Refresh
